### PR TITLE
Address more code review comments for SwiftIfConfig

### PR DESCRIPTION
**Pull request by DougGregor**
Address code review comments from https://github.com/swiftlang/swift-syntax/pull/2819

### CODE REVIEW

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
@swift-ci please test

**Comment by DougGregor** [comment]
I'm dropping the foldOperators caller changes for now.

**Comment by DougGregor** [comment]
@swift-ci please test Linux

**Comment by DougGregor** [comment]
@swift-ci please test Windows

**Review by ahoppen — COMMENTED** [review]
Thanks!

**Pull request merged**
