### PR TITLE
[sending] Get rid of transferring

### PR DESCRIPTION
**Pull request by gottesmm**
We left in support for transferring for a little bit. Now let's remove it.

This is the swift-syntax side of this:

https://github.com/swiftlang/swift/pull/74610

### CODE REVIEW

**Comment by gottesmm** [comment]
https://github.com/swiftlang/swift/pull/74610
@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/74610
@swift-ci test

**Review by ahoppen — APPROVED** [review]
Thanks for the cleanup, Michael.

**Comment by gottesmm** [comment]
https://github.com/swiftlang/swift/pull/74610
@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/swiftlang/swift/pull/74610
@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/apple/swift/pull/74610
@swift-ci test

**Comment by bnbarham** [comment]
apple/swift#74610

@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/swiftlang/swift/pull/74610

@swift-ci test

**Comment by shahmishal** [comment]
https://github.com/swiftlang/swift/pull/74610
@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/swiftlang/swift/pull/74610
@swift-ci test

**Comment by gottesmm** [comment]
https://github.com/swiftlang/swift/pull/74610
@swift-ci test

**Pull request merged**
