### PR TITLE
[CoroutineAccessors] Add read and modify.

### PR DESCRIPTION
**Pull request by nate-chandler**
Enable parsing the new keywords behind the CoroutineAccessors experimental feature.

### CODE REVIEW

**Review by ahoppen — APPROVED** [review]

**Comment by nate-chandler** [comment]
https://github.com/swiftlang/swift/pull/76526

@swift-ci please test

**Comment by nate-chandler** [comment]
https://github.com/swiftlang/swift/pull/76526

@swift-ci please test

**Comment by nate-chandler** [comment]
@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
https://github.com/swiftlang/swift/pull/76526

@swift-ci please test linux platform

**Comment by nate-chandler** [comment]
https://github.com/swiftlang/swift/pull/76526

@swift-ci please test

**Comment by nate-chandler** [comment]
https://github.com/swiftlang/swift/pull/76526

@swift-ci please test

**Comment by nate-chandler** [comment]
https://github.com/swiftlang/swift/pull/76526

@swift-ci please test

**Pull request merged**
