### PR TITLE
[SourceLocation] Add some doc-comments to VirtualFile type

### PR DESCRIPTION
**Pull request by rintaro**
Followup to #2900

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Review by ahoppen — APPROVED** [review]

**Comment by rintaro** [comment]
@swift-ci Please test macOS

**Comment by rintaro** [comment]
@swift-ci Please test macOS

**Comment by rintaro** [comment]
@swift-ci Please test macOS

**Pull request merged**
